version: "3" 
services: 
  express-app: 
    build: .
    ports: 
      - ${DOCKER_PORTS}
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DOCKER_URL}
  db:
    image: prismagraphql/mongo-single-replica:5.0.3
    ports: 
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD} 